name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check-and-test-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: [22, 24, 26]
    outputs:
      urls: ${{ steps.pkgprnew.outputs.urls }}
    steps:
      # v7
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

        # v2
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
        with:
          runtime: node@${{ matrix.node }}
          version: 11

      - run: pnpm ci
      - run: pnpm exec prettier --write ./pnpm-lock.yaml

      # Run checks and builds.
      - run: pnpm run check

      # Publish to pkgprnew to test publishing before actual publish.
      - name: Upload to pkgprnew. To test published package.
        id: pkgprnew
        if: matrix.node == 24
        run: pnpm dlx pkg-pr-new publish

  # Run tests against published package.
  test-published-package:
    runs-on: ubuntu-latest
    needs: check-and-test-publish
    strategy:
      matrix:
        typescript: ['3.5.0', 4, 5, 6, 7]
    steps:
      - run: 'echo ${{ needs.check-and-test-publish.outputs.urls }}'

      # v7
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
        with:
          runtime: node@24
          version: 11

      # Install only dev dependencies. Because the published package itself will have direct dependencies attached with it.
      - run: pnpm install --frozen-lockfile --dev
      - run: pnpm add --save-dev typescript@${{ matrix.typescript }}

      - name: Install the published package for testing
        run: pnpm add pkgprnew-published@${{ needs.check-and-test-publish.outputs.urls }}

      - name: Run tests against the published package
        run: pnpm exec turbo test
        env:
          TEST_PUBLISHED_PKG: 'true'
