name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  check-and-build:
    strategy:
      matrix:
        node: [22, 24, 26]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node }}
          version: 11
      - run: pnpm ci
      - run: pnpm exec prettier --write ./pnpm-lock.yaml
      - run: pnpm run check
      - run: pnpm run build
